target-version = "py312"  # should match minimal python version of PowerAPI

[lint]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "A",  # flake8-builtins
    "B",   # flake8-bugbear
    "G",   # flake8-logging-format
    "PT",  # flake8-pytest-style
    "UP",  # pyupgrade
    "ERA", # eradicate
    "RUF", # ruff-specific-rules
]

ignore = [
    "E501",   # line-too-long

    "F401",   # unused-import
]
