[build-system]
requires = ["uv_build >= 0.12.1, < 0.13"]
build-backend = "uv_build"

[project]
name = "powerapi"
description = "PowerAPI is a middleware toolkit for building software-defined power meters."
readme = "README.md"
keywords = ["powerapi", "energy", "power-meter", "green-computing"]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
requires-python = ">=3.12"
version = "2.10.0"

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

authors = [
    {name = "PowerAPI Staff", email = "powerapi-staff@inria.fr"},
]

dependencies = [
    "pyzmq >= 18.1.0",
    "setproctitle >= 1.1.8"
]

[project.optional-dependencies]
# Databases:
mongodb = ["pymongo >= 3.7.2"]
influxdb = ["influxdb-client >= 1.30.0"]
prometheus = ["prometheus-client >= 0.9.0"]
clickhouse = ["clickhouse-connect >= 1.0.0"]

# Plaforms:
kubernetes = ["kubernetes >= 27.0.2"]
openstack = ["openstacksdk >= 4.7.0"]

# Aliases:
all-databases = ["powerapi[mongodb, influxdb, prometheus, clickhouse]"]
all-platforms = ["powerapi[kubernetes, openstack]"]
everything = ["powerapi[all-databases, all-platforms]"]

[dependency-groups]
test = [
    "pytest >= 7.0.1",
    "pytest-timeout >= 1.4.2",
    "pytest-cov >= 4.0.0"
]

docs = [
    "sphinx >= 1.8.1",
    "sphinx-autodoc-typehints >= 1.6.0"
]

lint = [
    "ruff == 0.16.4"
]

dev = [
    {include-group = 'test'},
    {include-group = 'docs'},
    {include-group = 'lint'}
]

[project.urls]
homepage = "https://powerapi.org"
source = "https://github.com/powerapi-ng/powerapi"
tracker = "https://github.com/powerapi-ng/powerapi/issues"
